### PR TITLE
Add date32, date64, decimal128

### PR DESCRIPTION
**Pull request by johanpel**
Noticed a few fixed-size types weren't supported yet.
This adds support for Arrow's date32, date64 and decimal128

### CODE REVIEW

**Comment by johanpel** [comment]
Seems like there are a lot of deprecated functions in 0.16 that slipped through CI last time when we upgraded?

**Comment by mbrobbel** [comment]
> Seems like there are a lot of deprecated functions in 0.16 that slipped through CI last time when we upgraded?

It looks like a mix of 0.16 and 0.17 artifacts was installed. Looks like the Arrow team are releasing [0.17](https://lists.apache.org/thread.html/r40402e37afaf5ddffee4c80a44dd0e00ed91e73292f544e1d427080d%40%3Cdev.arrow.apache.org%3E). Because they don't seem to retain older releases (and we're not building from source in CI), we always get the latest version (because we have to apply a workaround), which causes these jobs to fail.

```
Setting up libarrow-glib-doc (0.17.0-1) ...
Setting up libarrow16:amd64 (0.16.0-1) ...
Setting up libarrow17:amd64 (0.17.0-1) ...
Setting up libgandiva-glib-doc (0.17.0-1) ...
Setting up libgandiva16:amd64 (0.16.0-1) ...
Setting up libgandiva17:amd64 (0.17.0-1) ...
Setting up libparquet-glib-doc (0.17.0-1) ...
Setting up libparquet16:amd64 (0.16.0-1) ...
Setting up libparquet17:amd64 (0.17.0-1) ...
Setting up libplasma-glib-doc (0.17.0-1) ...
Setting up libarrow-dataset16:amd64 (0.16.0-1) ...
Setting up libarrow-dataset17:amd64 (0.17.0-1) ...
Setting up libarrow-dev:amd64 (0.17.0-1) ...
Setting up libarrow-flight16:amd64 (0.16.0-1) ...
Setting up libarrow-flight17:amd64 (0.17.0-1) ...
Setting up libarrow-glib16:amd64 (0.16.0-1) ...
Setting up libarrow-glib17:amd64 (0.17.0-1) ...
Setting up libgandiva-dev:amd64 (0.17.0-1) ...
Setting up libgandiva-glib16:amd64 (0.16.0-1) ...
Setting up libgandiva-glib17:amd64 (0.17.0-1) ...
Setting up libparquet-dev:amd64 (0.17.0-1) ...
Setting up libparquet-glib16:amd64 (0.16.0-1) ...
Setting up libparquet-glib17:amd64 (0.17.0-1) ...
Setting up libarrow-dataset-dev:amd64 (0.17.0-1) ...
Setting up libarrow-flight-dev:amd64 (0.17.0-1) ...
```

**Comment by johanpel** [comment]
Easiest would be for us to migrate to 0.17 alongside Arrow, I'll do this some other time, so this might stay open for a bit

**Comment by mbrobbel** [comment]
@johanpel if you review + merge #223 and rebase this branch, it should be good to go.

**Comment by johanpel** [comment]
Going to fix this through #226

**Pull request closed without merging**
