### PR TITLE
Incorporate CompileUnits CMake module for C++ development

### PR DESCRIPTION
**Pull request by mbrobbel**
This is an attempt to incorporate the [CompileUnits](https://github.com/abs-tudelft/cmake-modules/tree/master/CompileUnits) module into Fletcher. The goal of this migration is to remove boilerplate from CMake files and produce predictable installation targets for our C++ code. The module is not perfect, poorly documented and changing frequently, but using it with Fletcher gives us the change to improve it.

There are some implications that we should be aware of.
1. This change depends on the [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) module of CMake, which was introduced in 3.13, and on the `FetchContent_MakeAvailable` function which was introduced in 3.14. This results in a bump of minimum CMake version required to build the project.
1. Currently the options are no longer the same as they are automatically generated for installable units (`SHARED` and `EXECUTABLE`).

# Todo
- [x] Migrate C++ targets to their corresponding "compilation units"
- [x] Fix `pyfletcher` build (https://github.com/mbrobbel/fletcher/pull/7)
- [x] Migrate CI to Azure Pipelines (https://github.com/mbrobbel/fletcher/pull/10)
- [x] Improve the test util structure
- [x] ~~Update documentation~~
- [x] Discuss default build targets and installation targets
- [x] ~~Setup example for CMake projects linking to Fletcher~~
- [x] ~~Fix CMake files for examples (https://github.com/mbrobbel/fletcher/pull/8)~~

We should keep this PR open for a while to make sure everything works as intended on all supported platforms. Stuff outside the scope of the initial release (#89) can be based off this branch.

### CODE REVIEW

**Comment by johanpel** [comment]
Getting this on cpp runtime, fletchgen (basically everything that depends on Arrow).

Seems there is some dependency on libarrow_cuda in the default arrow config?

```
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/arrow/arrowTargets.cmake:157 (message):
  The imported target "arrow_cuda_shared" references the file

     "/usr/lib/x86_64-linux-gnu/libarrow_cuda.so.13.0.0"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/x86_64-linux-gnu/cmake/arrow/arrowTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/arrow/arrowConfig.cmake:61 (include)
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
See also "workspace/fletcher/runtime/cpp/cmake-build-debug/CMakeFiles/CMakeOutput.log".
```

**Comment by mbrobbel** [comment]
@johanpel: this is a problem with the `arrowConfig.cmake` file that gets installed by Arrow. I've opened an issue for this: https://issues.apache.org/jira/browse/ARROW-5575
You can install the listed packages as a workaround, until Arrow fixes the issue with their packages. Check here for the workaround applied in ci: https://github.com/abs-tudelft/azure-pipelines-templates/blob/master/steps/install-arrow.yml#L13-L16

**Review by johanpel — COMMENTED** [review]
In terms of build system everything seems to be working fine.
I do get a few failing tests, checking this out now.

**Comment by johanpel** [comment]
It seems by default, after running `cmake ..` and `make test` in a build dir it doesn't set the LD_LIBRARY_DIR correctly to the echo subdirectory of the build dir.

Is this intended and should I do something about this myself or is the intention to do this automatically?

```
workspace/fletcher/runtime/cpp/debug$ CTEST_OUTPUT_ON_FAILURE=1 make test
Running tests...
Test project workspace/fletcher/runtime/cpp/debug
      Start  1: fletcher::test::Platform.NoPlatform
 1/12 Test  #1: fletcher::test::Platform.NoPlatform ....................................   Passed    0.01 sec
      Start  2: fletcher::test::Platform.EchoPlatform
 2/12 Test  #2: fletcher::test::Platform.EchoPlatform ..................................***Failed    0.00 sec
Running main() from gmock_main.cc
Note: Google Test filter = Platform.EchoPlatform
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Platform
[ RUN      ] Platform.EchoPlatform
[ERROR]: libfletcher_echo.so: cannot open shared object file: No such file or directory
workspace/fletcher/runtime/cpp/test/fletcher/test.cpp:37: Failure
Value of: fletcher::Platform::Make("echo", &platform, false).ok()
  Actual: false
Expected: true
[  FAILED  ] Platform.EchoPlatform (0 ms)
[----------] 1 test from Platform (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Platform.EchoPlatform

 1 FAILED TEST

      Start  3: fletcher::test::Context.ContextFunctions
 3/12 Test  #3: fletcher::test::Context.ContextFunctions ...............................***Failed    0.01 sec
Running main() from gmock_main.cc
Note: Google Test filter = Context.ContextFunctions
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Context
[ RUN      ] Context.ContextFunctions
[ERROR]: libfletcher_snap.so: cannot open shared object file: No such file or directory
[ERROR]: libfletcher_aws.so: cannot open shared object file: No such file or directory
[ERROR]: libfletcher_echo.so: cannot open shared object file: No such file or directory
workspace/fletcher/runtime/cpp/test/fletcher/test.cpp:71: Failure
Value of: fletcher::Platform::Make(&platform, false).ok()
  Actual: false
Expected: true
[  FAILED  ] Context.ContextFunctions (1 ms)
[----------] 1 test from Context (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Context.ContextFunctions

 1 FAILED TEST

....

83% tests passed, 2 tests failed out of 12

Total Test time (real) =   0.07 sec

The following tests FAILED:
	  2 - fletcher::test::Platform.EchoPlatform (Failed)
	  3 - fletcher::test::Context.ContextFunctions (Failed)
Errors while running CTest
Makefile:97: recipe for target 'test' failed
make: *** [test] Error 8
```

**Comment by mbrobbel** [comment]
Can you try `cmake .. -DBUILD_TESTS=ON && make && make test`? It should link to the echo platform in that case. Check the CMake file of the runtime: https://github.com/mbrobbel/fletcher/blob/compile-units/runtime/cpp/CMakeLists.txt#L18-L20

**Comment by johanpel** [comment]
> Can you try `cmake .. -DBUILD_TESTS=ON && make && make test`? It should link to the echo platform in that case. Check the CMake file of the runtime: https://github.com/mbrobbel/fletcher/blob/compile-units/runtime/cpp/CMakeLists.txt#L18-L20

Different machine, different problem...

Not sure where this threads is coming from. Is it googletest?

```
~/workspace/fletcher/runtime/cpp/debug$ cmake .. -DBUILD_TESTS=ON
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
CMake Error at debug/_deps/cmake-modules-src/CompileUnits/CompileUnits.cmake:245 (add_executable):
  Target "fletcher_test" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:54 (compile_units)


CMake Error at /home/johan/workspace/fletcher/runtime/cpp/debug/_deps/cmake-modules-src/CompileUnits/CompileUnits.cmake:245 (add_executable):
  Target "fletcher_common_test_common" links to target "Threads::Threads" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  /home/johan/workspace/fletcher/common/CMakeLists.txt:34 (compile_units)


CMake Error at /home/johan/workspace/fletcher/runtime/cpp/debug/_deps/cmake-modules-src/CompileUnits/CompileUnits.cmake:245 (add_executable):
  Target "fletcher_common_test_visitors" links to target "Threads::Threads"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  /home/johan/workspace/fletcher/common/CMakeLists.txt:34 (compile_units)


CMake Error at debug/_deps/cmake-modules-src/CompileUnits/CompileUnits.cmake:192 (add_library):
  Target "fletcher" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:54 (compile_units)


CMake Error at /home/johan/workspace/fletcher/runtime/cpp/debug/_deps/cmake-modules-src/CompileUnits/CompileUnits.cmake:192 (add_library):
  Target "fletcher_echo" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  /home/johan/workspace/fletcher/platforms/echo/runtime/CMakeLists.txt:28 (compile_units)


CMake Error at /home/johan/workspace/fletcher/runtime/cpp/debug/_deps/cmake-modules-src/CompileUnits/CompileUnits.cmake:192 (add_library):
  Target "fletcher_common" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  /home/johan/workspace/fletcher/common/CMakeLists.txt:34 (compile_units)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```



Adding this seems to fix this specific issue

```
set (THREADS_PREFER_PTHREAD_FLAG ON)
find_package (Threads REQUIRED)
```

But I don't think that should be placed in the CMake file of the runtime lib.

**Comment by johanpel** [comment]
> Can you try `cmake .. -DBUILD_TESTS=ON && make && make test`? It should link to the echo platform in that case. Check the CMake file of the runtime: https://github.com/mbrobbel/fletcher/blob/compile-units/runtime/cpp/CMakeLists.txt#L18-L20

Tried this on the original machine, but it doesn't work.
It does build the echo lib but make test doesn't seem to set the environment properly.

**Comment by mbrobbel** [comment]
Can you post the output of `ldd` on the echo platform test binary? The test passes in [ci](https://dev.azure.com/abs-tudelft/fletcher/_build/results?buildId=135&view=logs&jobId=1a34e779-8861-5512-25a4-cab8490a27ce) and on my machine.

Maybe relevant for the missing `Threads::Thread` target: https://github.com/google/googletest/blob/26afdba792e52cac00ce11644c3c0b1789c40bf7/googletest/cmake/internal_utils.cmake#L187 and this check here https://github.com/Kitware/CMake/blob/master/Modules/FindThreads.cmake#L147.

**Comment by johanpel** [comment]
For the machine with the Threads problem:

> Maybe relevant for the missing `Threads::Thread` target: https://github.com/google/googletest/blob/26afdba792e52cac00ce11644c3c0b1789c40bf7/googletest/cmake/internal_utils.cmake#L187 and this check here https://github.com/Kitware/CMake/blob/master/Modules/FindThreads.cmake#L147.

I don't think the problem is that pthread isn't found. Cmake says it did find phtreads. Take a look:

```
- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
```
then
```
-- Configuring done
CMake Error at debug/_deps/cmake-modules-src/CompileUnits/CompileUnits.cmake:192 (add_library):
  Target "fletcher_echo" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:28 (compile_units)

CMake Error at /home/johan/workspace/fletcher/platforms/echo/runtime/debug/_deps/cmake-modules-src/CompileUnits/CompileUnits.cmake:192 (add_library):
  Target "fletcher_common" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  /home/johan/workspace/fletcher/common/CMakeLists.txt:34 (compile_units)

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```


For the machine with the linking problem:

```
workspace/fletcher/runtime/cpp/debug$ ldd fletcher_test 
	linux-vdso.so.1 (0x00007ffc1d617000)
	libfletcher.so => workspace/fletcher/runtime/cpp/debug/libfletcher.so (0x00007f51bf299000)
	libarrow.so.13 => /usr/lib/x86_64-linux-gnu/libarrow.so.13 (0x00007f51beba8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f51be989000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f51be600000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f51be3e8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f51bdff7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f51bddf3000)
	libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007f51bdbe2000)
	libbrotlienc.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlienc.so.1 (0x00007f51bd95b000)
	libbrotlidec.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f51bd74f000)
	libglog.so.0 => /usr/lib/x86_64-linux-gnu/libglog.so.0 (0x00007f51bd51e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f51bd316000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f51bd0fa000)
	libsnappy.so.1 => /usr/lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007f51bcef2000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f51bccd5000)
	libzstd.so.1 => /usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f51bca5a000)
	libprotobuf.so.10 => /usr/lib/x86_64-linux-gnu/libprotobuf.so.10 (0x00007f51bc601000)
	libboost_system.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1 (0x00007f51bc3fc000)
	libboost_filesystem.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1 (0x00007f51bc1e2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f51bbe44000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f51bf7bf000)
	libbrotlicommon.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f51bbc24000)
	libgflags.so.2.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2.2 (0x00007f51bb9ff000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f51bb7e4000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f51bb5be000)
```

**Comment by johanpel** [comment]
Actually...

For the machine with the linking problem, LDD isn't going to show us anything since it's linked during run-time using dlopen.

During `make test` the environment should set such that through dlopen libfletcher_echo.so can be found.

**Comment by johanpel** [comment]
This fixes the linking problem for me. Is this supposed to happen somewhere automatically?
```
LD_LIBRARY_PATH=echo make test
```

**Comment by mbrobbel** [comment]
Can you post the output of the fletcher_test build and link step with `make VERBOSE=1`?
And can you post the output of `objdump -x fletcher_test | grep -n10 RPATH`?

**Comment by johanpel** [comment]
> Can you post the output of the fletcher_test build and link step with `make VERBOSE=1`?

I guess you're interested in this:

```
/usr/bin/c++     CMakeFiles/fletcher_test.dir/test/fletcher/test.cpp.o  -o fletcher_test -Wl,-rpath,/home/jhpeltenburg/workspace/fletcher/runtime/cpp/debug:/home/jhpeltenburg/workspace/fletcher/runtime/cpp/debug/echo libfletcher.so echo/libfletcher_echo.so lib/libgmock_main.a /usr/lib/x86_64-linux-gnu/libarrow.so.13.0.0 -ldl lib/libgmock.a lib/libgtest.a -lpthread 
```

That seems to be the proper rpath... Any idea why it doesn't turn up in the object dump?

> And can you post the output of `objdump -x fletcher_test | grep -n10 RPATH`?

```
objdump -x fletcher_test | grep -n10 RPATH
```
Outputs nothing.

**Comment by johanpel** [comment]
It seems to show up as:

  RUNPATH              /home/jhpeltenburg/workspace/fletcher/runtime/cpp/debug:/home/jhpeltenburg/workspace/fletcher/runtime/cpp/debug/echo

**Comment by mbrobbel** [comment]
From scratch on linux: (centos 7.6)
```
/usr/bin/c++     CMakeFiles/fletcher_test.dir/test/fletcher/test.cpp.o  -o fletcher_test -Wl,-rpath,/home/matthijsbrobbe/fletcher/build:/home/matthijsbrobbe/fletcher/build/echo libfletcher.so echo/libfletcher_echo.so lib/libgmock_main.a /usr/lib64/libarrow.so.13.0.0 -ldl lib/libgmock.a lib/libgtest.a -lpthread
```

```
readelf -d fletcher_test

Dynamic section at offset 0xa1d98 contains 33 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libfletcher.so]
 0x0000000000000001 (NEEDED)             Shared library: [libfletcher_echo.so]
 0x0000000000000001 (NEEDED)             Shared library: [libarrow.so.13]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000f (RPATH)              Library rpath: [/home/matthijsbrobbe/fletcher/build:/home/matthijsbrobbe/fletcher/build/echo]
```

```
make test
Running tests...
Test project /home/matthijsbrobbe/fletcher/build
      Start  1: fletcher::test::Platform.NoPlatform
 1/12 Test  #1: fletcher::test::Platform.NoPlatform ....................................   Passed    0.03 sec
      Start  2: fletcher::test::Platform.EchoPlatform
 2/12 Test  #2: fletcher::test::Platform.EchoPlatform ..................................   Passed    0.03 sec
      Start  3: fletcher::test::Context.ContextFunctions
 3/12 Test  #3: fletcher::test::Context.ContextFunctions ...............................   Passed    0.02 sec
```

Can you check `printenv` to make sure nothing unintentionally influences the build process?

**Comment by johanpel** [comment]
This explains the problem quite well:

https://stackoverflow.com/questions/47117443/dynamic-linking-with-rpath-not-working-under-ubuntu-17-10

**Comment by johanpel** [comment]
- [x] Depend on Arrow 0.14 for ABI incompatibility problems
- [x] Re-add top level CMake file

**Pull request merged**
